Repository StateVoicesNational/Spoke, pull requests merged in 2018-07, with the labels that each got.

#691 Fix dev-nowrap
  package.json
Labels: ready for stage

#682 Stage main
  __test__/AssignmentSummary.test.js
  __test__/server/api/assignment.test.js
  src/components/AssignmentSummary.jsx
  src/components/CampaignContactsForm.jsx
  src/components/CampaignTextersForm.jsx
  src/components/IncomingMessageFilter.jsx
  src/components/IncomingMessageList.jsx
  src/containers/AdminCampaignEdit.jsx
  src/containers/AdminIncomingMessageList.jsx
  src/containers/TexterTodoList.jsx
  src/routes.jsx
  src/server/api/assignment.js
  src/server/api/conversations.js
  src/server/api/errors.js
  src/server/api/lib/twilio.js
  src/server/api/schema.js
  src/server/models/custom-types.js
Labels: ready for stage

#686 #628: "Send First Texts" button disables properly
  src/components/AssignmentSummary.jsx
Labels: ready for stage

#689 Don't wipe out all assignments when entering a number of contacts > unassigned contacts
  src/components/CampaignTextersForm.jsx
Labels: ready for stage

#695 Don't need organization.assignments ...
  src/containers/AdminIncomingMessageList.jsx
Labels: ready for stage

#699 add missing await to accessRequired
  src/server/api/errors.js
Labels: ready for stage

#702 Removes opt outs from initial assignments query - not sure we ever ha…
  __test__/server/api/assignment.test.js
  src/server/api/assignment.js
Labels: bug, ready for stage, testing in production

#731 Stage main [2]
  __test__/backend.test.js
  __test__/lib.test.js
  __test__/server/api/assignment.test.js
  src/api/assignment.js
  src/api/campaign-contact.js
  src/api/campaign.js
  src/api/canned-response.js
  src/api/conversations.js
  src/api/interaction-step.js
  src/api/invite.js
  src/api/message.js
  src/api/opt-out.js
  src/api/organization.js
  src/api/question-response.js
  src/api/question.js
  src/api/schema.js
  src/api/user.js
  src/components/CampaignTextersForm.jsx
  src/components/ContactToolbar.jsx
  src/containers/AdminCampaignEdit.jsx
  src/containers/AssignmentTexterContact.jsx
  src/lib/timezones.js
  src/server/api/assignment.js
  src/server/api/campaign-contact.js
  src/server/api/campaign.js
  src/server/api/canned-response.js
  src/server/api/conversations.js
  src/server/api/interaction-step.js
  src/server/api/invite.js
  src/server/api/message.js
  src/server/api/opt-out.js
  src/server/api/organization.js
  src/server/api/question-response.js
  src/server/api/question.js
  src/server/api/schema.js
  src/server/api/user.js
  src/server/index.js
Labels: testing in production

#715 Fix issue 709
  src/components/CampaignTextersForm.jsx
Labels: ready for stage
