Repository StateVoicesNational/Spoke, pull requests merged in 2018-08, with the labels that each got.

#755 Stage main
  __test__/workers/jobs.test.js
  docs/REFERENCE-environment_variables.md
  jest.config.js
  lambda.js
  src/components/AssignmentSummary.jsx
  src/components/CampaignContactsForm.jsx
  src/components/Navigation.jsx
  src/components/TexterFAQs.jsx
  src/components/TexterFaqs.jsx
  src/containers/AssignmentTexterContact.jsx
  src/migrations/index.js
  src/server/api/assignment.js
  src/server/api/campaign.js
  src/server/api/message.js
  src/server/api/organization.js
  src/server/api/schema.js
  src/server/models/message.js
  src/workers/job-processes.js
  src/workers/jobs.js
  webpack/config.js
Labels: testing in production

#524 draft plan for scaling message-response cycle with redis
  docs/HOWTO-scale-spoke-plan.md
Labels: needs planning, scaling, server-side (nodejs)

#770 Added tools for developing in Docker
  Dockerfile
  README.md
  docker-compose.yml
Labels: ready for stage

#788 Stage main 2
  src/containers/AssignmentTexterContact.jsx
  src/lib/attributes.js
  src/server/api/schema.js
  src/server/middleware/render-index.js
  webpack/config.js
Labels: ready for stage, testing in production

#750 Bug Fix: Fixes #742 Remove User.id Error on Homepage
  src/server/api/schema.js
Labels: ready for stage

#761 Safer passing of node env to client to ensure dev test code isnt running
  src/lib/attributes.js
  src/server/middleware/render-index.js
Labels: ready for stage

#777 Adds inblock display to smaller screen sizes and decrease left margin
  src/containers/AssignmentTexterContact.jsx
Labels: ready for stage
