Repository StateVoicesNational/Spoke, pull requests merged in 2018-10, with the labels that each got.

#961 fixing scaling-message bugs on stage
  src/server/api/schema.js
Labels: ready for stage, testing-on-stage

#953 Stage main 2
  .travis.yml
  __test__/e2e/page-functions/campaigns.js
  __test__/e2e/page-objects/campaigns.js
  jest.config.e2e.js
  package.json
  src/api/campaign.js
  src/containers/CampaignList.jsx
  src/server/api/campaign.js
Labels: testing in production

#962 Scaling by stream contacts
  lambda.js
  package.json
  src/server/api/schema.js
  src/server/index.js
  src/server/models/cacheable_queries/campaign-contact.js
Labels: ready for stage, scaling, testing-on-stage

#976 Stage main
  .gitignore
  docs/REFERENCE-environment_variables.md
  package.json
  src/api/organization.js
  src/api/schema.js
  src/components/CampaignContactsForm.jsx
  src/containers/AdminPersonList.jsx
  src/lib/phone-format.js
  src/server/api/organization.js
  src/server/api/schema.js
  src/server/api/user.js
  src/workers/job-processes.js
  src/workers/jobs.js
Labels: testing in production

#986 connect opportunistically to DataWarehouse
  src/server/models/datawarehouse.js
  src/workers/jobs.js
Labels: ready for stage

#982 Lambda version for assign texters
  src/workers/job-processes.js
  src/workers/jobs.js
Labels: ready for stage

#988 opportunistically open the warehouse connection -- otherwise, dont co…
  src/server/models/datawarehouse.js
  src/workers/jobs.js
Labels: testing in production, testing on beta

#993 accept twilio messages with special characters
  lambda.js
Labels: ready for stage, testing in production, testing-on-stage
