Repository StateVoicesNational/Spoke, pull requests merged in 2018-09, with the labels that each got.

#768 Removes ability to change initial script in texter view
  src/containers/AssignmentTexterContact.jsx
Labels: priority: 1, ready for stage, testing-on-stage

#812 Changes file structure to separate out user caching logic and export …
  src/server/api/errors.js
  src/server/auth-passport.js
  src/server/models/cacheable_queries/index.js
  src/server/models/cacheable_queries/user.js
Labels: ready for stage, testing-on-stage

#824 linted migrations file
  src/migrations/index.js
Labels: ready for stage, testing-on-stage

#851 document some security codepoints
  docs/EXPLANATION-development-guidelines.md
Labels: documentation

#864 Stage main 2
  __test__/server/api/assignment.test.js
  docs/HOWTO_INTEGRATE_WITH_REVERE.md
  docs/REFERENCE-environment_variables.md
  src/api/campaign.js
  src/api/schema.js
  src/containers/AdminCampaignEdit.jsx
  src/containers/AdminCampaignList.jsx
  src/server/action_handlers/revere-signup.js
  src/server/api/assignment.js
  src/server/api/campaign.js
  src/server/api/schema.js
  src/server/api/user.js
  src/server/models/cacheable_queries/user.js
  src/workers/jobs.js
Labels: testing in production, testing-on-stage

#794 606 revere v2
  docs/HOWTO_INTEGRATE_WITH_REVERE.md
  docs/REFERENCE-environment_variables.md
  src/server/action_handlers/revere-signup.js
Labels: moveon-team-specific, priority: 1, ready for stage, testing-on-stage

#816 799 admin campaign list loading
  src/api/campaign.js
  src/containers/AdminCampaignList.jsx
  src/server/api/campaign.js
Labels: ready for stage, testing-on-stage

#844 fix ambiguous user_id error
  src/server/api/user.js
Labels: ready for stage, testing-on-stage

#866 Put cell numbers through formatter
  src/workers/jobs.js
Labels: bug

#833 optimization: we only use the allContactsCount not all the ids, so just get the count
  src/components/AssignmentTexter.jsx
  src/containers/TexterTodo.jsx
Labels: ready for stage

#868 migration is not triggered when we are not creating the db
  src/server/index.js
Labels: ready for stage

#880 force display on graphQL errors
  src/network/errors.js
Labels: ready for stage

#893 817 sqlitefix
  src/server/api/campaign.js
Labels: ready for stage, scaling

#898 added sorting to post-scaling query to load canned responses from db
  src/server/models/cacheable_queries/canned-response.js
Labels: ready for stage

#916 WIP - refactor user.js in cacheable queries
  src/server/api/campaign.js
  src/server/api/errors.js
  src/server/auth-passport.js
  src/server/models/cacheable_queries/assignment.js
  src/server/models/cacheable_queries/campaign-contact.js
  src/server/models/cacheable_queries/campaign.js
  src/server/models/cacheable_queries/canned-response.js
  src/server/models/cacheable_queries/index.js
  src/server/models/cacheable_queries/opt-out.js
  src/server/models/cacheable_queries/organization.js
  src/server/models/cacheable_queries/user.js
  src/server/models/index.js
Labels: scaling, wip

#933 Some tests of assignTexters
  __test__/workers/assign-texters.test.js
  jest.config.js
Labels: ready for stage
