Repository StateVoicesNational/Spoke, pull requests merged in 2019-12, with the labels that each got.

#1281 HOWTO-run_tests - added link to tips in getting postgres installed
  README.md
  docs/HOWTO-run_tests.md
Labels: C-documentation, S-ready for stage-main (qa)

#1280 Update google-libphonenumber
  package.json
  yarn.lock
Labels: S-ready for stage-main (qa)

#1278 Canceling a new Canned Response
  src/components/CampaignCannedResponseForm.jsx
  src/components/CampaignCannedResponsesForm.jsx
Labels: S-needs tests, S-ready for stage-main (qa)

#1285 Improve documentation for bulk sending outside the USA.
  docs/HOWTO-use_bulk_sending_outside_the_USA.md
  docs/REFERENCE-environment_variables.md
Labels: C-documentation

#1279 Document GOOGLE_SECRET
  docs/REFERENCE-environment_variables.md
Labels: C-documentation, S-ready for stage-main (qa)

#1260 Guide to buying numbers through Twilio
  docs/HOWTO_BUY_NUMBERS_IN_TWILIO.md
  docs/images/twilio_number_buying_guide/blurred_number_purchased.png
  docs/images/twilio_number_buying_guide/buy_number_button.png
  docs/images/twilio_number_buying_guide/messaging_services.png
  docs/images/twilio_number_buying_guide/numbers_menu.png
  docs/images/twilio_number_buying_guide/programmable_sms_menu.png
  docs/images/twilio_number_buying_guide/sms_menu.png
  docs/images/twilio_number_buying_guide/spoke_app_name.png
Labels: C-documentation, S-ready for stage-main (qa)
