Repository StateVoicesNational/Spoke, pull requests merged in 2019-06, with the labels that each got.

#1119 Stage main 2
  .env.example
  README.md
  __test__/components/AssignmentTexter.test.js
  __test__/containers/TexterTodo.test.js
  __test__/test_client_helpers.js
  app.json
  docs/DEPLOYING_AWS_LAMBDA.md
  docs/EXPLANATION-development-guidelines.md
  docs/HOWTO-configure-auth0.md
  docs/HOWTO_HEROKU_DEPLOY.md
  docs/MESSAGE REVIEW documentation
  docs/REFERENCE-environment_variables.md
  src/components/AssignmentTexter.jsx
  src/components/IncomingMessageList/ConversationPreviewModal.jsx
  src/containers/AssignmentTexterContact.jsx
  src/containers/TexterTodo.jsx
  src/containers/TexterTodoList.jsx
  src/migrations/index.js
  src/server/api/schema.js
Labels: testing in production

#1107 Use the sequence for canned_response ids
  src/migrations/index.js
  src/server/api/schema.js
Labels: needs qa round, qa staging round, ready for stage

#1112 🐞view conversations (in message review) won't open
  src/components/IncomingMessageList/ConversationPreviewModal.jsx
Labels: needs qa round, ready for stage
