Repository StateVoicesNational/Spoke, pull requests merged in 2019-07, with the labels that each got.

#1150 Stage main
  .nvmrc
  .travis.yml
  Dockerfile
  README.md
  __test__/server/render-index.test.js
  dev-tools/Procfile.dev
  docs/HOWTO_USE_POSTGRESQL.md
  package.json
  src/api/organization.js
  src/api/schema.js
  src/components/ContactToolbar.jsx
  src/containers/AdminCampaignEdit.jsx
  src/containers/AdminPersonList.jsx
  src/containers/AdminScriptImport.jsx
  src/containers/PaginatedUsersRetriever.jsx
  src/lib/pendingJobsUtils.js
  src/migrations/index.js
  src/server/api/lib/import-script..js
  src/server/api/organization.js
  src/server/api/schema.js
  src/server/api/user.js
  src/server/middleware/render-index.js
  src/server/models/cacheable_queries/campaign.js
  src/workers/job-processes.js
  src/workers/jobs.js
  yarn.lock
Labels: testing in production, testing-on-stage

#1140 add a title= attr to contact firstname so on-hover provides debug info
  src/components/ContactToolbar.jsx
Labels: needs qa round, ready for stage

#1145 fix sqlite for migration that was postgres-specific
  src/migrations/index.js
Labels: needs qa round, ready for stage

#1146 update rethink-knex-adapter to 0.4.18
  package.json
  yarn.lock
Labels: needs qa round, ready for stage

#1160 Stage main 2
  .gitattributes
  dev-tools/README.md
  docs/HOWTO_HEROKU_DEPLOY.md
  src/api/schema.js
  src/components/ContactToolbar.jsx
  src/containers/AssignmentTexterContact.jsx
  src/containers/TexterTodo.jsx
  src/server/api/schema.js
  src/server/api/user.js
  src/server/notifications.js
Labels: testing in production, testing-on-stage

#1132 disable cacheable flag for now, since full assignment info is not yet…
  src/server/api/user.js
Labels: ready for stage

#1139 remove rootQuery contact
  src/api/schema.js
  src/server/api/schema.js
Labels: needs qa round, ready for stage

#1176 Stage main
  .travis.yml
  __test__/backend.test.js
  __test__/server/api/campaign.test.js
  __test__/server/db/export.js
  __test__/server/db/utils.js
  __test__/server/texter.test.js
  __test__/test_helpers.js
  docs/DEPLOYING_AWS_LAMBDA.md
  docs/EXPLANATION-development-guidelines.md
  knexfile.env.js
  migrations/20190207220000_init_db.js
  package.json
  src/components/AssignmentTexter.jsx
  src/components/CampaignInteractionStepsForm.jsx
  src/containers/AdminCampaignEdit.jsx
  src/containers/AdminIncomingMessageList.jsx
  src/containers/TexterTodo.jsx
  src/containers/TexterTodoList.jsx
  src/lib/interaction-step-helpers.js
  src/migrations/index.js
  src/server/api/question.js
  src/server/api/schema.js
  src/server/index.js
  src/server/knex-connect.js
  src/server/models/cacheable_queries/campaign.js
  src/server/models/cacheable_queries/canned-response.js
  src/server/models/cacheable_queries/index.js
  src/server/models/cacheable_queries/lib.js
  src/server/models/cacheable_queries/opt-out.js
  src/server/models/cacheable_queries/organization.js
  src/server/models/index.js
  src/server/models/migrations.js
  src/server/models/thinky.js
  src/workers/job-processes.js
  yarn.lock
Labels: testing in production
