Repository StateVoicesNational/Spoke, pull requests merged in 2019-11, with the labels that each got.

#1261 SQL - all responses to Initial text, substring JSON data
  docs/TEXTER_ACTIVITY_QUERIES.md
Labels: C-documentation

#1257 Issue #1239: Fix code syntax highlighting in TEXTER_ACTIVITIES_QUERIES
  docs/TEXTER_ACTIVITY_QUERIES.md
Labels: C-documentation, S-ready for stage

#1253 Create HOWTO_CODE_REVIEW.md
  docs/HOWTO_CODE_REVIEW.md
Labels: C-documentation, S-qa staging round, S-testing-on-stage

#1247 Fix to canned responses
  src/containers/AssignmentTexterContact.jsx
Labels: S-qa staging round, S-testing-on-stage

#1243 Enough already. Give TexterF[qa|AQ]s.jsx a completely new name
  __test__/components/TexterFrequentlyAskedQuestions.test.js
  src/components/TexterFaqs.jsx
  src/components/TexterFrequentlyAskedQuestions.jsx
  src/routes.jsx
Labels: S-needs qa round, S-qa staging round, S-ready for stage

#1236 Add explicit reference to `PGSSLMODE=require`
  docs/HOWTO_HEROKU_DEPLOY.md
Labels: C-documentation, S-qa staging round, S-ready for stage, S-testing-on-stage

#1233 Update ROLES_DESCRIPTION.md
  docs/ROLES_DESCRIPTION.md
Labels: C-documentation, S-qa staging round, S-ready for stage, S-testing-on-stage

#1229 Changed "canned responses" to "other responses"
  src/containers/AssignmentTexterContact.jsx
Labels: S-needs qa round, S-qa staging round, S-ready for stage, S-testing-on-stage
