Repository StateVoicesNational/Spoke, pull requests merged in 2020-07, with the labels that each got.

#1658 Roll back react-formal upgrade because it breaks 'select' fields
  package.json
  yarn.lock
Labels: S-ready for stage-main (qa)

#1660 Add HackNight working group to the CONTRIBUTING doc
  CONTRIBUTING.md
Labels: S-ready for stage-main (qa)

#1668 NGPVAN action handler tweaks
  src/integrations/action-handlers/ngpvan-action.js
  src/server/lib/http-request.js
Labels: S-ready for stage-main (qa)

#1654 Configurable background processing backends with bull and lambda implementations
  __test__/integrations/action-handlers/index.test.js
  __test__/server/api/campaign/updateQuestionResponses.test.js
  __test__/server/api/updateContactTags.test.js
  src/integrations/action-handlers/complex-test-action.js
  src/integrations/action-handlers/index.js
  src/integrations/action-handlers/test-action.js
  src/integrations/action-handlers/zapier-action.js
  src/integrations/job-runners/README.md
  src/integrations/job-runners/experimental-bull/README.md
  src/integrations/job-runners/experimental-bull/index.js
  src/integrations/job-runners/experimental-bull/processor.js
  src/integrations/job-runners/experimental-bull/queues.js
  src/integrations/job-runners/helpers.js
  src/integrations/job-runners/index.js
  src/integrations/job-runners/lambda-async/handler.js
  src/integrations/job-runners/lambda-async/index.js
  src/integrations/job-runners/legacy.js
  src/server/api/lib/utils.js
  src/server/api/mutations/buyPhoneNumbers.js
  src/server/api/mutations/sendMessage.js
  src/server/api/mutations/updateContactTags.js
  src/server/api/mutations/updateQuestionResponses.js
  src/server/api/schema.js
  src/workers/job-handler.js
  src/workers/job-processes.js
  src/workers/tasks.js
Labels: S-ready for stage-main (qa)

#1672 NGP VAN permissive cellphone selection
  __test__/integrations/action-handlers/ngpvan-action.test.js
  __test__/integrations/contact-loaders/ngpvan/ngpvan.test.js
  src/integrations/action-handlers/ngpvan-action.js
  src/integrations/contact-loaders/ngpvan/index.js
  src/integrations/message-handlers/ngpvan/index.js
Labels: S-ready for stage-main (qa)

#1670 add onFocus to open canned response dialog and add empty string to state
  src/components/forms/GSScriptField.jsx
Labels: S-ready for stage-main (qa)

#1679 Add character/segment counts to ScriptEditor
  package.json
  src/components/ScriptEditor.jsx
  yarn.lock
Labels: S-ready for stage-main (qa)

#1683 bugfix: update campaign assignedCount on dynamic assignment
  src/server/api/mutations/findNewCampaignContact.js
Labels: S-on deck, S-ready for stage-main (qa)

#1663 reduced flash for initial text to avoid jarring UI
  src/components/AssignmentTexter/Controls.jsx
  src/containers/AssignmentTexterContact.jsx
  src/styles/theme.js
Labels: S-ready for stage-main (qa)

#1659 Fix saving terms agreement
  src/server/api/schema.js
Labels: S-ready for stage-main (qa)

#1655 More message handlers around profanity
  __test__/integrations/message-handlers/profanity-tagger.test.js
  src/integrations/message-handlers/auto-optout/index.js
  src/integrations/message-handlers/index.js
  src/integrations/message-handlers/profanity-tagger/index.js
  src/server/api/lib/twilio.js
  src/server/api/mutations/sendMessage.js
  src/server/models/cacheable_queries/message.js
Labels: S-ready for stage-main (qa)

#1650 ctrl-Enter to send from Ctrl-x conflicting as a Cut command
  src/components/AssignmentTexter/Controls.jsx
Labels: S-ready for stage-main (qa)

#1649 Slack auth
  docs/HOWTO_INTEGRATE_SLACK_AUTH.md
  package.json
  src/client/auth-service.js
  src/components/Login.jsx
  src/containers/PeopleList.jsx
  src/server/auth-passport.js
  src/server/index.js
  yarn.lock
Labels: S-ready for stage-main (qa)

#1646 Add tags to campaign exports
  src/workers/jobs.js
Labels: S-ready for stage-main (qa)

#1635 heroku deploy: add redis addon by default with maxmemory-policy
  app.json
Labels: A-deployment, S-ready for stage-main (qa)
