Repository StateVoicesNational/Spoke, pull requests merged in 2020-04, with the labels that each got.

#1485 contact-loaders: allow per-organization setting for CONTACT_LOADERS
  src/integrations/contact-loaders/index.js
  src/server/api/schema.js
Labels: S-ready for stage-main (qa)

#1468 bugfix: change bitwise-OR to OR operator
  src/containers/TexterTodo.jsx
Labels: S-ready for stage-main (qa)

#1459 Create a quick link for deploying a production set up to Heroku
  README.md
  app.json
  src/components/SendButton.jsx
  src/lib/scripts.js
  src/server/api/user.js
Labels: S-ready for stage-main (qa)

#1448 Refactor parse-csv
  __test__/integrations/contact-loaders/csv-upload.test.js
  __test__/lib/parse-csv.test.js
  src/integrations/contact-loaders/csv-upload/react-component.js
  src/lib/index.js
  src/lib/parse_csv.js
Labels: S-ready for stage-main (qa)

#1446 upgrade node version to 10.x and twilio
  .nvmrc
  docs/DEPLOYING_AWS_LAMBDA.md
  package.json
  src/server/api/lib/twilio.js
  src/server/index.js
  yarn.lock
Labels: S-ready for stage-main (qa)

#1435 Feature Request: Streamline, add field labels and improve usability of the Account view (Issue #1357)
  src/containers/UserEdit.jsx
Labels: S-ready for stage-main (qa)

#1408 WIP: Scaling 2020 - PR 3 - message caching
  __test__/containers/CampaignList.test.js
  __test__/server/api/campaign.test.js
  __test__/server/api/lib/twilio.test.js
  src/api/campaign.js
  src/containers/CampaignList.jsx
  src/server/api/assignment.js
  src/server/api/campaign-contact.js
  src/server/api/campaign.js
  src/server/api/lib/fakeservice.js
  src/server/api/lib/message-sending.js
  src/server/api/lib/twilio.js
  src/server/api/message.js
  src/server/api/mutations/sendMessage.js
  src/server/api/schema.js
  src/server/models/cacheable_queries/campaign-contact.js
  src/server/models/cacheable_queries/campaign.js
  src/server/models/cacheable_queries/index.js
  src/server/models/cacheable_queries/message.js
  src/server/models/cacheable_queries/opt-out.js
  src/server/models/cacheable_queries/organization.js
  src/server/models/cacheable_queries/question-response.js
  src/workers/jobs.js
Labels: S-work in progress (WIP)

#1510 Set up cypress and add campaign and sign up tests
  .gitignore
  __test__/cypress/fixtures/test-data.js
  __test__/cypress/fixtures/two-contacts.csv
  __test__/cypress/integration/basic-campaign-e2e.test.js
  __test__/cypress/integration/local-auth.test.js
  __test__/cypress/plugins/index.js
  __test__/cypress/plugins/tasks.js
  __test__/cypress/plugins/utils.js
  __test__/cypress/support/index.js
  cypress.json
  docs/EXPLANATION-end-to-end-tests.md
  docs/HOWTO-run_tests.md
  jest.config.js
  package.json
  src/components/AssignmentSummary.jsx
  src/components/CampaignBasicsForm.jsx
  src/components/CampaignTextersForm.jsx
  src/components/forms/GSDateField.jsx
  src/containers/UserEdit.jsx
  src/integrations/contact-loaders/csv-upload/react-component.js
  src/lib/attributes.js
  yarn.lock
Labels: S-ready for stage-main (qa)

#1378 Heroku One-Click Deployment documentation
  docs/HOWTO-configure-auth0.md
Labels: C-documentation, S-ready for stage-main (qa)

#1507 scaling documentation additions
  docs/EXPLANATION-development-guidelines.md
  docs/HOWTO-scale-spoke-plan.md
  src/server/models/cacheable_queries/README.md
Labels: C-documentation
