Repository StateVoicesNational/Spoke, pull requests merged in 2020-09, with the labels that each got.

#1808 datawarehouse contact-loaders fixes
  src/extensions/contact-loaders/datawarehouse/index.js
  src/extensions/contact-loaders/datawarehouse/react-component.js
  src/workers/job-processes.js
Labels: S-ready for stage-main (qa)

#1803 job to update optouts regularly in case the update fails and for autoupdates where it does not update by default
  src/server/models/cacheable_queries/opt-out.js
  src/workers/job-processes.js
Labels: S-ready for stage-main (qa)

#1804 speed up deduplication query
  __test__/extensions/contact-loaders/csv-upload.test.js
  src/workers/jobs.js
Labels: S-ready for stage-main (qa)

#1802 filter contact fields to just what is in scripts and cannedresponses
  src/lib/interaction-step-helpers.js
  src/lib/scripts.js
  src/server/api/campaign-contact.js
  src/server/api/schema.js
  src/server/models/cacheable_queries/campaign.js
  src/server/models/cacheable_queries/canned-response.js
Labels: S-ready for stage-main (qa)

#1795 Allows downtime deployment
  docs/REFERENCE-environment_variables.md
  lambda.js
  src/components/AssignmentTexter/Demo.jsx
  src/components/Downtime.jsx
  src/containers/Home.jsx
  src/routes.jsx
  src/server/downtime.js
  src/server/middleware/render-index.js
Labels: S-ready for stage-main (qa)

#1801 two additional custom fields for tracking the contact by id
  src/lib/scripts.js
Labels: S-ready for stage-main (qa)

#1791 campaign edit: convos and stats links
  src/containers/AdminCampaignEdit.jsx
  src/containers/AdminCampaignStats.jsx
Labels: S-ready for stage-main (qa)

#1770 Add importing of response tags
  docs/HOWTO_IMPORT_GOOGLE_DOCS_SCRIPTS_TO_IMPORT.md
  src/server/api/lib/import-script.js
Labels: S-ready for stage-main (qa)

#1434 Past campaign contact loader
  __test__/extensions/contact-loaders/csv-upload.test.js
  src/components/CampaignContactsChoiceForm.jsx
  src/components/IncomingMessageActions.jsx
  src/containers/AdminIncomingMessageList.jsx
  src/extensions/contact-loaders/past-contacts/index.js
  src/extensions/contact-loaders/past-contacts/react-component.js
  src/extensions/contact-loaders/test-fakedata/index.js
  src/lib/conversations.js
  src/lib/index.js
  src/server/api/conversations.js
  src/server/models/cacheable_queries/campaign.js
Labels: A-contact loaders, S-ready for stage-main (qa), S-work in progress (WIP)

#1826 for backwards compatibility we need to validation when TWILIO_STATUS_CALLBACK_URL
  app.json
  docs/HOWTO_INTEGRATE_TWILIO.md
  docs/REFERENCE-environment_variables.md
  src/server/api/lib/twilio.js
  src/server/index.js
Labels: S-ready for stage-main (qa)

#1858 S3pull contactloader for loading from a S3 bucket dumped from Redshift
  src/extensions/contact-loaders/s3-pull/index.js
  src/extensions/contact-loaders/s3-pull/react-component.js
  src/workers/job-processes.js
Labels: S-work in progress (WIP)
