Repository StateVoicesNational/Spoke, pull requests merged in 2020-06, with the labels that each got.

#1602 Return to request-scoped data loaders
  __test__/integrations/action-handlers/index.test.js
  __test__/server/api/campaign/updateQuestionResponses.test.js
  src/integrations/action-handlers/complex-test-action.js
  src/integrations/action-handlers/index.js
  src/integrations/contact-loaders/csv-upload/index.js
  src/integrations/contact-loaders/datawarehouse/index.js
  src/integrations/contact-loaders/index.js
  src/integrations/contact-loaders/ngpvan/index.js
  src/integrations/contact-loaders/test-fakedata/index.js
  src/server/api/conversations.js
  src/server/api/mutations/bulkSendMessages.js
  src/server/api/mutations/buyPhoneNumbers.js
  src/server/api/mutations/editOrganization.js
  src/server/api/mutations/sendMessage.js
  src/server/api/schema.js
  src/server/models/cacheable_queries/campaign-contact.js
  src/server/models/cacheable_queries/campaign.js
  src/server/models/cacheable_queries/organization.js
  src/server/models/cacheable_queries/user.js
  src/server/models/index.js
Labels: S-on deck

#1603 Add a logout button for orgless users, fix data loading on login
  src/containers/Home.jsx
Labels: S-on deck

#1604 Remove broken message received notifications
  src/server/notifications.js
Labels: S-on deck

#1609 Fix convo link when there is only an initial message
  src/components/IncomingMessageList/ConversationPreviewModal.jsx
  src/integrations/texter-sideboxes/contact-reference/react-component.js
  src/routes.jsx
Labels: C-bug, O-wfp-priority

#1615 require contact response before exposing the message review view
  src/components/IncomingMessageList/index.jsx
Labels: S-ready for stage-main (qa)

#1626 Fix cacheableData queries in texting hour mutations
  src/server/api/schema.js
Labels: S-ready for stage-main (qa)
