Repository StateVoicesNational/Spoke, pull requests merged in 2020-02, with the labels that each got.

#1389 Optouts should be Opt-outs in admin dashboard nav
  src/components/AdminDashboard.jsx
Labels: S-ready for stage-main (qa)

#1379 enable tests for editUser in backend.test.js
  __test__/backend.test.js
Labels: S-ready for stage-main (qa)

#1360 change testdata numbers to numbers reserved for "Hollywood" 555-0100 => 555-0199
  __test__/test_data/female_scientists.csv
Labels: S-on deck

#1396 updated step 1 of install
  README.md
Labels: C-documentation

#1342 Add comment reminding us to reevaluate optimization of interaction steps loading after react >=16 upgrade
  src/components/CampaignInteractionStepsForm.jsx
Labels: S-ready for stage-main (qa)

#1417 Prettierrc file
  .eslintrc
  .prettierrc
  package.json
  yarn.lock
Labels: S-on deck

#1419 Expand instructions for how to update your Spoke instance on Heroku t…
  docs/HOWTO_HEROKU_DEPLOY.md
Labels: C-documentation
