Repository StateVoicesNational/Spoke, pull requests merged in 2020-08, with the labels that each got.

#1715 fix GSScriptEditor for Safari browsers that auto-focus
  src/components/forms/GSScriptField.jsx
Labels: S-ready for stage-main (qa)

#1711 Remove the whole-page scrollbar by fixing the sidebar height
  src/components/AdminDashboard.jsx
Labels: S-ready for stage-main (qa)

#1709 Add an environment variable for database debugging
  .env.example
  docs/REFERENCE-environment_variables.md
  src/server/knex-connect.js
Labels: S-ready for stage-main (qa)

#1706 initialtext-guard message-handler: disable texting if the initial message is changed
  src/integrations/message-handlers/initaltext-guard/index.js
  src/server/api/lib/twilio.js
  src/server/api/mutations/sendMessage.js
  src/server/models/cacheable_queries/message.js
  src/workers/jobs.js
Labels: S-ready for stage-main (qa)

#1704 Add US state to phone inventory page
  package.json
  src/api/organization.js
  src/containers/AdminPhoneNumberInventory.js
  src/server/api/organization.js
  yarn.lock
Labels: S-ready for stage-main (qa)

#1702 Dynamic assignment batches
  .env.example
  __test__/components/AssignmentSummary.test.js
  __test__/components/AssignmentTexter/ContactController.test.js
  app.json
  src/api/assignment.js
  src/api/schema.js
  src/components/AssignmentSummary.jsx
  src/components/AssignmentTexter/ContactController.jsx
  src/components/AssignmentTexter/Controls.jsx
  src/components/AssignmentTexter/Demo.jsx
  src/components/AssignmentTexter/StyleControls.js
  src/components/CampaignDynamicAssignmentForm.jsx
  src/components/CampaignTexterUIForm.jsx
  src/containers/AssignmentTexterContact.jsx
  src/containers/TexterTodo.jsx
  src/containers/TexterTodoList.jsx
  src/integrations/dynamicassignment-batches/finished-replies/index.js
  src/integrations/dynamicassignment-batches/index.js
  src/integrations/dynamicassignment-batches/vetted-texters/index.js
  src/integrations/texter-sideboxes/celebration-gif/react-component.js
  src/integrations/texter-sideboxes/components.js
  src/integrations/texter-sideboxes/contact-reference/react-component.js
  src/integrations/texter-sideboxes/default-dynamicassignment/react-component.js
  src/integrations/texter-sideboxes/release-contacts/react-component.js
  src/integrations/texter-sideboxes/tag-contact/react-component.js
  src/routes.jsx
  src/server/api/assignment.js
  src/server/api/campaign.js
  src/server/api/mutations/bulkSendMessages.js
  src/server/api/mutations/findNewCampaignContact.js
  src/server/api/mutations/releaseContacts.js
  src/server/api/schema.js
  src/server/api/user.js
  src/server/local-auth-helpers.js
  src/server/models/campaign.js
Labels: S-ready for stage-main (qa)

#1700 Fix VAN action handler with warehouse loader
  src/integrations/action-handlers/ngpvan-action.js
Labels: S-ready for stage-main (qa)

#1695 fixes issue #587: blocking blank message sending
  src/components/AssignmentTexter/Controls.jsx
Labels: S-ready for stage-main (qa)

#1699 Simplify the README by changing .env.example
  .env.example
  README.md
Labels: S-ready for stage-main (qa)

#1691 update campaign.needsResponseCount when optout without a response
  src/api/schema.js
  src/containers/AssignmentTexterContact.jsx
  src/integrations/message-handlers/auto-optout/index.js
  src/server/api/schema.js
  src/server/models/cacheable_queries/opt-out.js
Labels: S-ready for stage-main (qa)

#1688 VAN input type is optional
  __test__/integrations/action-handlers/ngpvan-action.test.js
  src/integrations/action-handlers/ngpvan-action.js
Labels: S-ready for stage-main (qa)

#1686 Include action handlers with Google Docs script import
  src/server/api/lib/import-script.js
Labels: S-ready for stage-main (qa)

#1678 Per-campaign phone number management
  __test__/server/api/campaign/campaign.test.js
  __test__/test_helpers.js
  docs/REFERENCE-environment_variables.md
  migrations/20200613153306_add_owned_phone_number_index.js
  src/api/campaign.js
  src/api/organization.js
  src/api/schema.js
  src/components/AdminCampaignList/CampaignTable.jsx
  src/components/CampaignPhoneNumbersForm.jsx
  src/containers/AdminCampaignEdit.jsx
  src/containers/AdminCampaignList.jsx
  src/containers/AdminCampaignStats.jsx
  src/integrations/job-runners/legacy.js
  src/server/api/campaign.js
  src/server/api/lib/owned-phone-number.js
  src/server/api/lib/twilio.js
  src/server/api/mutations/index.js
  src/server/api/mutations/releaseCampaignNumbers.js
  src/server/api/mutations/startCampaign.js
  src/server/api/organization.js
  src/server/api/schema.js
  src/server/middleware/render-index.js
  src/workers/job-processes.js
  src/workers/jobs.js
Labels: S-ready for stage-main (qa)

#1737 [WIP] First draft of a doc for dynamic assignment
  docs/HOWTO-use-dynamicassignment-batches.md
  docs/RELEASE_NOTES.md
Labels: S-ready for stage-main (qa)

#1731 Fix contributor covenant link by using underscores
  README.md
Labels: S-on deck, T-hackathon

#1766 leading - in campaign search excludes the search term
  src/server/api/campaign.js
Labels: S-ready for stage-main (qa)

#1764 Small phone inventory improvements
  src/containers/AdminPhoneNumberInventory.js
Labels: S-ready for stage-main (qa)

#1760 Docsify
  docs/.nojekyll
  docs/HOWTO-run_tests.md
  docs/HOWTO_CONNECT_WITH_REDIS.md
  docs/MESSAGE_REVIEW_documentation.md
  docs/README.md
  docs/_sidebar.md
  docs/index.html
Labels: S-ready for stage-main (qa)

#1755 [WIP] Message review query
  src/components/IncomingMessageFilter.jsx
  src/containers/AdminIncomingMessageList.jsx
Labels: O-moveon-priority, S-ready for stage-main (qa)

#1749 1714: Updating texter filter in Campaign/texters screen
  src/components/CampaignTextersForm.jsx
Labels: S-on deck, S-ready for stage-main (qa)

#1752 fix message sending where additional context info needs to be sent fo…
  src/workers/job-processes.js
  src/workers/jobs.js
Labels: O-moveon-priority, S-on deck, S-ready for stage-main (qa)

#1747 Freshworks widget texter sidebox
  .env.example
  src/extensions/texter-sideboxes/freshworks-widget/react-component.js
Labels: S-ready for stage-main (qa)

#1746 Add support for Twilio error 21408
  src/server/api/lib/twilio.js
Labels: S-ready for stage-main (qa)

#1745 Tag resolution MVP -- server changes
  __test__/server/api/updateContactTags.test.js
  __test__/server/models/cacheable_queries/tag-campaign-contact.test.js
  src/api/schema.js
  src/containers/AssignmentTexterContact.jsx
  src/extensions/texter-sideboxes/tag-contact/react-component.js
  src/server/api/campaign-contact.js
  src/server/models/cacheable_queries/index.js
  src/server/models/cacheable_queries/tag-campaign-contact.js
Labels: O-moveon-priority, S-ready for stage-main (qa)

#1743 Left-justify outgoing message text and add some padding to the messag…
  src/components/AssignmentTexter/MessageList.jsx
  src/components/AssignmentTexter/StyleControls.js
Labels: S-ready for stage-main (qa)

#1744 Add more info about safely using Redis with multiple Spoke instances
  docs/HOWTO_CONNECT_WITH_REDIS.md
Labels: C-documentation

#1736 Ensure that interactions are copied deterministically
  src/server/api/schema.js
Labels: S-on deck, S-ready for stage-main (qa)

#1738 Copy all relevant campaign properties when copying a campaign
  __test__/backend.test.js
  src/containers/AdminCampaignStats.jsx
  src/server/api/schema.js
Labels: S-on deck, S-ready for stage-main (qa)

#1735 Remove the scroll bars in every cell in the people table
  src/containers/PeopleList.jsx
Labels: S-on deck, S-ready for stage-main (qa)

#1722 Remove the scroll bars in every cell in the incoming-messages table
  src/components/IncomingMessageList/index.jsx
Labels: S-on deck

#1710 Receive Twilio messages from behind a proxy using TWILIO_MESSAGE_CALLBACK_URL
  .env.example
  docs/HOWTO_INTEGRATE_TWILIO.md
  docs/REFERENCE-environment_variables.md
  src/server/api/lib/twilio.js
  src/server/index.js
Labels: S-ready for stage-main (qa)

#1705 Feature #1645: Canned response tag association
  __test__/components/CampaignCannedResponseForm.test.js
  __test__/components/CampaignCannedResponsesForm.test.js
  __test__/components/TagChips.test.js
  __test__/server/api/campaign/campaign.test.js
  __test__/server/api/updateContactTags.test.js
  __test__/server/db/utils.js
  __test__/test_helpers.js
  jest.config.js
  migrations/20200701185642_addTagCannedResponseTable.js
  src/api/canned-response.js
  src/api/schema.js
  src/components/AssignmentTexter/Controls.jsx
  src/components/CampaignCannedResponseForm.jsx
  src/components/CampaignCannedResponsesForm.jsx
  src/components/TagChips.jsx
  src/containers/AdminCampaignEdit.jsx
  src/containers/AssignmentTexterContact.jsx
  src/containers/TexterTodo.jsx
  src/server/api/canned-response.js
  src/server/api/lib/utils.js
  src/server/api/mutations/bulkSendMessages.js
  src/server/api/mutations/sendMessage.js
  src/server/api/mutations/updateContactTags.js
  src/server/api/schema.js
  src/server/models/cacheable_queries/canned-response.js
  src/server/models/index.js
  src/server/models/tag-campaign-contact.js
  src/server/models/tag-canned-response.js
Labels: O-moveon-priority, S-ready for stage-main (qa)
