Repository StateVoicesNational/Spoke, pull requests merged in 2020-05, with the labels that each got.

#1519 Campaign table with sorting and filtering
  __test__/containers/CampaignList.test.js
  __test__/server/api/organization.test.js
  __test__/test_helpers.js
  package.json
  src/api/campaign.js
  src/api/organization.js
  src/api/schema.js
  src/components/AdminCampaignList/CampaignTable.jsx
  src/components/AdminCampaignList/SortBy.jsx
  src/components/DualNavDataTables/TableToolbar.jsx
  src/components/DualNavDataTables/index.jsx
  src/components/Paginated/PaginatedList.jsx
  src/components/Paginated/withPagination.jsx
  src/components/Search.jsx
  src/components/TableToolbar.jsx
  src/containers/AdminCampaignList.jsx
  src/containers/CampaignList.jsx
  src/containers/TexterTodo.jsx
  src/integrations/contact-loaders/index.js
  src/server/api/campaign.js
  src/server/api/lib/import-script.js
  src/server/api/lib/nexmo.js
  src/server/api/organization.js
  src/server/api/schema.js
  src/server/models/cacheable_queries/campaign.js
  yarn.lock
Labels: S-qa staging round, S-ready for stage-main (qa)

#1509 track campaign.errorCount in cache
  __test__/server/api/lib/twilio.test.js
  src/api/campaign.js
  src/server/api/campaign.js
  src/server/api/lib/twilio.js
  src/server/models/cacheable_queries/campaign-contact.js
  src/server/models/cacheable_queries/campaign.js
  src/server/models/cacheable_queries/message.js
Labels: S-qa staging round, S-ready for stage-main (qa)

#1490 ci: Add Github Actions, code coverage
  .github/workflows/jest-tests.yaml
  __test__/backend.test.js
  package.json
Labels: S-qa staging round, S-ready for stage-main (qa)

#1481 Have nodemon send SIGTERM when restarting due to changes
  package.json
Labels: S-qa staging round, S-ready for stage-main (qa)

#1534 AssignmentTexter refactor
  __test__/components/AssignmentTexter/ContactController.test.js
  __test__/components/AssignmentTexter/Survey.test.js
  src/components/AssignmentTexter/BulkSendButton.jsx
  src/components/AssignmentTexter/CannedResponseMenu.jsx
  src/components/AssignmentTexter/ContactController.jsx
  src/components/AssignmentTexter/Controls.jsx
  src/components/AssignmentTexter/Demo.jsx
  src/components/AssignmentTexter/MessageList.jsx
  src/components/AssignmentTexter/OldControls.jsx
  src/components/AssignmentTexter/OldToolbar.jsx
  src/components/AssignmentTexter/ScriptList.jsx
  src/components/AssignmentTexter/SendButtonArrow.jsx
  src/components/AssignmentTexter/Survey.jsx
  src/components/AssignmentTexter/Toolbar.jsx
  src/containers/AssignmentTexterContact.jsx
  src/containers/TexterTodo.jsx
  src/routes.jsx
Labels: S-ready for stage-main (qa), S-work in progress (WIP)

#1548 Update HOWTO_INTEGRATE_TWILIO.md
  docs/HOWTO_INTEGRATE_TWILIO.md
Labels: C-documentation

#1557 Stage phone number management and campaign messaging service changes
  .env.example
  __test__/cypress/integration/basic-campaign-e2e.test.js
  __test__/cypress/integration/local-auth.test.js
  __test__/cypress/integration/phone-inventory.test.js
  __test__/cypress/plugins/index.js
  __test__/cypress/plugins/tasks.js
  __test__/cypress/plugins/utils.js
  __test__/server/api/campaign/campaign.test.js
  __test__/server/api/lib/twilio.test.js
  __test__/test_helpers.js
  dev-tools/buy-numbers.js
  docs/REFERENCE-environment_variables.md
  jest.config.js
  migrations/20200422002041_add_messaging_sid_to_campaign.js
  migrations/20200428162145_add_phone_number_table_and_change_job_request.js
  migrations/helpers/index.js
  package.json
  src/api/campaign.js
  src/api/organization.js
  src/api/schema.js
  src/components/AdminDashboard.jsx
  src/components/CampaignMessagingServiceForm.jsx
  src/containers/AdminCampaignEdit.jsx
  src/containers/AdminCampaignMessagingService.jsx
  src/containers/AdminCampaignStats.jsx
  src/containers/AdminPhoneNumberInventory.js
  src/routes.jsx
  src/server/api/campaign.js
  src/server/api/lib/__mocks__/twilio.js
  src/server/api/lib/fakeservice.js
  src/server/api/lib/services.js
  src/server/api/lib/twilio.js
  src/server/api/mutations/buyPhoneNumbers.js
  src/server/api/mutations/index.js
  src/server/api/organization.js
  src/server/api/schema.js
  src/server/middleware/render-index.js
  src/server/models/campaign.js
  src/server/models/index.js
  src/server/models/job-request.js
  src/server/models/owned_phone_number.js
  src/workers/job-processes.js
  src/workers/jobs.js
Labels: S-ready for stage-main (qa)

#1554 Migration To Add Roles VETTED_TEXTER, ORG_SUPERADMIN, SUSPENDED
  migrations/20190207220000_init_db.js
  migrations/20200512143258_add_user_roles.js
  src/server/models/user-organization.js
Labels: S-ready for stage-main (qa)

#1575 Document shortcut rules for the new Texter UI
  docs/REFERENCE-shortcut-rules.md
Labels: C-documentation

#1570 remove coverage test from github actions which always times-out
  .github/workflows/jest-tests.yaml
Labels: S-ready for stage-main (qa)

#1561 Required text inputs on the campaign basics tab
  src/components/CampaignBasicsForm.jsx
Labels: S-ready for stage-main (qa)

#1555 Fix Buggy Environment variables reference claims
  src/server/knex-connect.js
Labels: S-ready for stage-main (qa)

#1531 Show contact upload progress with contact loaders
  src/containers/AdminCampaignEdit.jsx
Labels: S-ready for stage-main (qa)

#1525 Phone number inventory management
  __test__/cypress/integration/basic-campaign-e2e.test.js
  __test__/cypress/integration/local-auth.test.js
  __test__/cypress/integration/phone-inventory.test.js
  __test__/cypress/plugins/index.js
  __test__/cypress/plugins/tasks.js
  __test__/cypress/plugins/utils.js
  __test__/server/api/lib/twilio.test.js
  docs/REFERENCE-environment_variables.md
  migrations/20200428162145_add_phone_number_table_and_change_job_request.js
  migrations/helpers/index.js
  src/api/organization.js
  src/api/schema.js
  src/components/AdminDashboard.jsx
  src/containers/AdminPhoneNumberInventory.js
  src/routes.jsx
  src/server/api/lib/fakeservice.js
  src/server/api/lib/services.js
  src/server/api/lib/twilio.js
  src/server/api/mutations/buyPhoneNumbers.js
  src/server/api/mutations/index.js
  src/server/api/organization.js
  src/server/api/schema.js
  src/server/middleware/render-index.js
  src/server/models/index.js
  src/server/models/job-request.js
  src/server/models/owned_phone_number.js
  src/workers/job-processes.js
  src/workers/jobs.js
Labels: S-ready for stage-main (qa)

#1500 Add title to campaign edit
  src/containers/AdminCampaignEdit.jsx
Labels: S-ready for stage-main (qa)

#1416 [1362] Feature Request: Change the label on the "Send Replies" button…
  __test__/AssignmentSummary.test.js
  src/components/AssignmentSummary.jsx
Labels: S-ready for stage-main (qa)
