Repository StateVoicesNational/Spoke, pull requests merged in 2021-01, with the labels that each got.

#1857 Fix startCampaign when campaign phone number are enabled in org settings
  src/server/api/mutations/startCampaign.js
Labels: S-postelection STABLE candidate

#1865 deleted help text
  src/containers/AdminCampaignList.jsx
Labels: S-postelection STABLE candidate

#1881 Delete phone numbers from inventory and Twilio
  src/api/schema.js
  src/containers/AdminPhoneNumberInventory.js
  src/server/api/lib/fakeservice.js
  src/server/api/lib/twilio.js
  src/server/api/mutations/buyPhoneNumbers.js
  src/server/api/mutations/index.js
  src/server/api/organization.js
  src/server/api/schema.js
  src/workers/job-processes.js
  src/workers/jobs.js
Labels: S-postelection UNSTABLE candidate

#1898 Change -1 error message to not suggest an automatic retry
  src/server/api/lib/twilio.js
Labels: S-post-election 2020 stable, S-ready for stage-main (qa)

#1790 Canned response search
  __test__/components/AssignmentTexter/Survey.test.js
  __test__/lib/search-helpers.test.js
  src/components/AssignmentTexter/Controls.jsx
  src/components/AssignmentTexter/Survey.jsx
  src/lib/search-helpers.js
Labels: S-postelection UNSTABLE candidate

#1805 Stop needMessageCount input from zeroing-out
  src/components/CampaignTextersForm.jsx
Labels: S-postelection STABLE candidate

#1814 Allow admins to see phone inventory
  src/components/AdminDashboard.jsx
  src/containers/AdminPhoneNumberInventory.js
  src/server/api/organization.js
Labels: S-postelection UNSTABLE candidate

#1835 VAN message handler -- improved error handling
  __test__/extensions/message-handlers/ngpvan.test.js
  src/extensions/message-handlers/ngpvan/index.js
Labels: S-postelection STABLE candidate

#1840 Move Action Network handler to extensions folder
  __test__/extensions/action-handlers/action-network.test.js
  src/extensions/action-handlers/action-network.js
Labels: S-postelection STABLE candidate

#1841 Run dispatchProcesses on Heroku
  package.json
  src/heroku/heroku-dispatch.js
Labels: S-postelection STABLE candidate

#1845 message review: allow Unassign assignment action
  src/api/schema.js
  src/components/IncomingMessageActions.jsx
  src/server/api/conversations.js
Labels: S-postelection STABLE candidate

#1855 Add ability to reorder survey questions via buttons "bump", "top" and "bottom" WIP
  src/components/CampaignInteractionStepsForm.jsx
Labels: S-postelection UNSTABLE candidate

#1863 Run Cypress end-to-end tests in CI/Github Actions
  .github/workflows/cypress-tests.yaml
  README.md
  __test__/cypress/fixtures/test-data.js
  __test__/cypress/integration/basic-campaign-e2e.test.js
  __test__/cypress/integration/local-auth.test.js
  __test__/cypress/integration/phone-inventory.test.js
  __test__/cypress/integration/user-edit.test.js
  __test__/cypress/plugins/index.js
  __test__/cypress/plugins/tasks.js
  __test__/cypress/plugins/utils.js
  __test__/cypress/support/commands.js
  __test__/cypress/support/index.js
  __test__/e2e/.env.e2e
  __test__/e2e/basic_text_manager.test.js
  __test__/e2e/create_copy_campaign.test.js
  __test__/e2e/create_edit_campaign.test.js
  __test__/e2e/data/people.csv
  __test__/e2e/data/strings.js
  __test__/e2e/invite_texter.test.js
  __test__/e2e/page-functions/campaigns.js
  __test__/e2e/page-functions/index.js
  __test__/e2e/page-functions/login.js
  __test__/e2e/page-functions/main.js
  __test__/e2e/page-functions/people.js
  __test__/e2e/page-functions/texter.js
  __test__/e2e/page-objects/campaigns.js
  __test__/e2e/page-objects/index.js
  __test__/e2e/page-objects/login.js
  __test__/e2e/page-objects/main.js
  __test__/e2e/page-objects/navigation.js
  __test__/e2e/page-objects/people.js
  __test__/e2e/page-objects/scriptEditor.js
  __test__/e2e/page-objects/texter.js
  __test__/e2e/util/config.js
  __test__/e2e/util/helpers.js
  __test__/e2e/util/setup.js
  __test__/test_helpers.js
  cypress.json
  dev-tools/.env.test
  dev-tools/Procfile.test
  docs/HOWTO-run_tests.md
  jest.config.e2e.js
  jest.config.js
  package.json
  src/lib/attributes.js
  src/server/middleware/app-renderer.jsx
  travis-run-e2e-tests
  webpack/config.js
  webpack/server.js
  yarn.lock
Labels: S-postelection STABLE candidate

#1866 Allow texters to (optionally) see MMS media content
  migrations/20201001164842_message_media.js
  src/api/message.js
  src/components/AssignmentTexter/MessageList.jsx
  src/containers/TexterTodo.jsx
  src/server/api/lib/twilio.js
  src/server/api/message.js
  src/server/models/cacheable_queries/message.js
  src/server/models/message.js
Labels: S-postelection UNSTABLE candidate

#1869 Clear user cache when creating org
  src/containers/AdminOrganizationsDashboard.jsx
  src/server/api/schema.js
Labels: S-postelection STABLE candidate
