Repository StateVoicesNational/Spoke, pull requests merged in 2021-04, with the labels that each got.

#1899 CSS Fix for UI alignment
  src/components/AssignmentTexter/Toolbar.jsx
Labels: S-ready for stage-main (qa)

#1926 ScriptEditor cursor position
  src/components/ScriptEditor.jsx
Labels: S-ready for stage-main (qa)

#1929 No yellow badges
  __test__/components/AssignmentSummary.test.js
  src/components/AssignmentSummary.jsx
Labels: S-ready for stage-main (qa)

#1935 Fix #1910: Bump Auth0 Lock to v11.28
  docs/HOWTO-configure-auth0.md
Labels: S-ready for stage-main (qa)

#1948 MobileCommons extrafields
  docs/HOWTO_INTEGRATE_WITH_MOBILE_COMMONS.md
  src/extensions/action-handlers/mobilecommons-signup.js
  src/extensions/contact-loaders/test-fakedata/index.js
  src/extensions/message-handlers/auto-optout/index.js
Labels: S-ready for stage-main (qa)

#1958 Export all contacts including those without assignment
  src/workers/jobs.js
Labels: S-ready for stage-main (qa)

#1959 Mobilize event shifter autofill data fixes
  src/extensions/texter-sideboxes/mobilize-event-shifter/react-component.js
Labels: A-client side (react), C-bug, S-ready for stage-main (qa)

#1960 Message review table overflow visible for long tags & truncate long tag text
  src/components/IncomingMessageList/index.jsx
  src/components/TagChip.jsx
Labels: A-Texter UI/UX, S-ready for stage-main (qa)

#1962 Assignment feedback saving dialog
  src/extensions/texter-sideboxes/texter-feedback/react-component.js
Labels: S-ready for stage-main (qa)

#1963 Feedback config
  src/extensions/texter-sideboxes/texter-feedback/AssignmentTexterFeedback.jsx
  src/server/api/campaign.js
Labels: C-bug, S-ready for stage-main (qa)

#1964 Change s3cmd to aws cli
  docs/HOWTO_DEPLOYING_AWS_LAMBDA.md
  package.json
Labels: A-deployment, C-documentation, S-ready for stage-main (qa)

#1967 Add ability to also suppress Tags in Message Review
  src/api/campaign-contact.js
  src/components/IncomingMessageFilter.jsx
  src/components/TagsSelector.jsx
  src/containers/AdminIncomingMessageList.jsx
  src/lib/conversations.js
  src/server/api/conversations.js
Labels: A-message review, C-enhancement, S-ready for stage-main (qa)

#1972 texter todos: gather unassigned checks into a single query instead of per-assignment
  src/extensions/dynamicassignment-batches/all-texters/index.js
  src/extensions/dynamicassignment-batches/finished-replies/index.js
  src/extensions/dynamicassignment-batches/vetted-takeconversations/index.js
  src/extensions/dynamicassignment-batches/vetted-texters/index.js
  src/server/api/assignment.js
  src/server/api/user.js
Labels: S-ready for stage-main (qa)

#1946 Update REFERENCE-environment_variables.md and Update and rename HOWTO_BUY_NUMBERS_IN_TWILIO.md to HOWTO_BUY_NUMBERS_IN_SPOKE.md
  docs/HOWTO_BUY_NUMBERS_IN_SPOKE.md
  docs/HOWTO_BUY_NUMBERS_IN_TWILIO.md
  docs/REFERENCE-environment_variables.md
  docs/_sidebar.md
Labels: C-documentation

#1932 Return informative errors from GraphQL endpoint
  src/server/index.js
Labels: S-ready for stage-main (qa)

#1968 Replacing SHOW/CLOSE Menu elements with IconButtons
  src/components/Navigation.jsx
Labels: S-ready for stage-main (qa)
